bootstrap:
  annotations: {}
  labels: {}
  tolerations: []
  nodeSelector: {}
  backoffLimit: 4
  patchConfigMap:
    name: ""
    data: {}
  bootstrap:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    env:
      apiUrl:
      clusterName:
    image:
      repository: registry.ciroos.ai/ciroos/bootstrap
      tag: 71513238f-02b3aa6c1-260402T1415Z
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 128Mi
  serviceAccount:
    annotations: {}
token:
  secretName: ciroos-token
  token: ""
uninstaller:
  annotations: {}
  labels: {}
  tolerations: []
  nodeSelector: {}
  uninstall:
    args:
      - --skip-projectsveltos=false
    image:
      repository: registry.ciroos.ai/ciroos/uninstaller
      tag: bfd285221-2974753e1-260402T1435Z