apiVersion: v1
kind: ServiceAccount
metadata:
  name: ciroos-uninstaller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: register-mgmt-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ciroos-uninstaller
  namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ciroos-uninstaller
  namespace: default
spec:
  ttlSecondsAfterFinished: 240
  template:
    spec:
      containers:
      - name: uninstall
        image: registry.ciroos.ai/ciroos/uninstaller:6dbe31455-amd64
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      serviceAccountName: ciroos-uninstaller
      restartPolicy: Never
  backoffLimit: 4
---
