{{- if .Values.namespaceScoped }}
apiVersion: lib.ciroos.ai/v1beta1
kind: NamespacedResourceWatcher
metadata:
  name: deployment-watcher
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  alwaysSend: false
  resources:
  - dependencyRules:
    - direction: inbound
      expression: |
        [{
          "kind": "Namespace",
          "apiVersion": "v1",
          "name": resource.metadata.namespace,
          "namespace": ""
        }]
      name: namespace
      type: containment
    groupVersionKind:
      group: apps
      kind: Deployment
      version: v1
    matchRules:
    - expression: "true"
      name: all-deployment
    name: deployment
{{- else }}
apiVersion: lib.ciroos.ai/v1beta1
kind: ResourceWatcher
metadata:
  name: deployment-watcher
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  alwaysSend: false
  resources:
  - dependencyRules:
    - direction: inbound
      expression: |
        [{
          "kind": "Namespace",
          "apiVersion": "v1",
          "name": resource.metadata.namespace,
          "namespace": ""
        }]
      name: namespace
      type: containment
    groupVersionKind:
      group: apps
      kind: Deployment
      version: v1
    matchRules:
    - expression: "true"
      name: all-deployment
    name: deployment
{{- end }}