{{- if .Values.namespaceScoped }}
apiVersion: lib.ciroos.ai/v1beta1
kind: NamespacedResourceWatcher
metadata:
  name: pod-watcher-pvc
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  alwaysSend: false
  resources:
  - dependencyRules:
    - direction: outbound
      expression: |
        has(resource.spec.volumes) ?
          resource.spec.volumes
            .filter(vol, has(vol.persistentVolumeClaim))
            .map(vol, {
              "kind": "PersistentVolumeClaim",
              "apiVersion": "v1",
              "name": vol.persistentVolumeClaim.claimName,
              "namespace": resource.metadata.namespace
            }) : []
      name: pvc-mounts
      type: storage
    groupVersionKind:
      group: ""
      kind: Pod
      version: v1
    matchRules:
    - expression: "true"
      name: all-pods
    name: running-pods
{{- else }}
apiVersion: lib.ciroos.ai/v1beta1
kind: ResourceWatcher
metadata:
  name: pod-watcher-pvc
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  alwaysSend: false
  resources:
  - dependencyRules:
    - direction: outbound
      expression: |
        has(resource.spec.volumes) ?
          resource.spec.volumes
            .filter(vol, has(vol.persistentVolumeClaim))
            .map(vol, {
              "kind": "PersistentVolumeClaim",
              "apiVersion": "v1",
              "name": vol.persistentVolumeClaim.claimName,
              "namespace": resource.metadata.namespace
            }) : []
      name: pvc-mounts
      type: storage
    groupVersionKind:
      group: ""
      kind: Pod
      version: v1
    matchRules:
    - expression: "true"
      name: all-pods
    name: running-pods
{{- end }}