apiVersion: v1
kind: ServiceAccount
metadata:
  name: beacon-sa
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.beaconSa.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-discovery
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceDiscovery.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventrouter-controller
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.eventrouterController.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector
  labels:
    app.kubernetes.io/component: Agent
  {{- include "ciroos-agents.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.vector.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: source-repository-watcher-controller
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.sourceRepositoryWatcherController.serviceAccount.annotations | nindent 4 }}