apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: service-discovery
    {{- include "ciroos-agents.selectorLabels" . | nindent 4 }}
  ports:
  - name: service-discovery-grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  - name: service-discovery-prometheus
    port: 7010
    protocol: TCP
    targetPort: 7010