apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: beacon-clusterrolebinding
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'beacon-clusterrole'
subjects:
- kind: ServiceAccount
  name: 'beacon-sa'
  namespace: '{{ .Release.Namespace }}'