{{- if .Values.namespaceScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: beacon-role
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
{{- if .Values.beacon.impersonate }}
- apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  verbs:
  - "impersonate"
  {{- if .Values.beacon.impersonatedServiceAccounts }}
  resourceNames:
    {{- toYaml .Values.beacon.impersonatedServiceAccounts | nindent 4 }}
  {{- end }}
{{- end }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beacon-clusterrole
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
{{- if .Values.beacon.impersonate }}
- apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  verbs:
  - "impersonate"
  {{- if .Values.beacon.impersonatedServiceAccounts }}
  resourceNames:
    {{- toYaml .Values.beacon.impersonatedServiceAccounts | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}