{{- if .Values.namespaceScoped }}
apiVersion: lib.ciroos.ai/v1beta1
kind: NamespacedAlert
metadata:
  name: critical-event-alert
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  matchRules:
  - expression: resource.reason in ['CreateContainerError']
    name: critical-pod-events
{{- else }}
apiVersion: lib.ciroos.ai/v1beta1
kind: Alert
metadata:
  name: critical-event-alert
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  matchRules:
  - expression: resource.reason in ['CreateContainerError']
    name: critical-pod-events
{{- end }}