apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ebpf-topo-reducer
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  - daemonsets
  - statefulsets
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ebpf-topo-reducer
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'ebpf-topo-reducer'
subjects:
- kind: ServiceAccount
  name: 'ebpf-topo-reducer'
  namespace: '{{ .Release.Namespace }}'