apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eventrouter-leader-election-role
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eventrouter-leader-election-rolebinding
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'eventrouter-leader-election-role'
subjects:
- kind: ServiceAccount
  name: 'eventrouter-controller'
  namespace: '{{ .Release.Namespace }}'