apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventrouter-manager-rolebinding
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'eventrouter-controller-role'
subjects:
- kind: ServiceAccount
  name: 'eventrouter-controller'
  namespace: '{{ .Release.Namespace }}'