{{- if .Values.namespaceScoped }}
apiVersion: lib.ciroos.ai/v1beta1
kind: NamespacedAlert
metadata:
  name: generic-failures-alert
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  matchRules:
  - expression: resource.reason == 'Failed' && !resource.message.matches('(?i).*(health
      check|readiness|liveness).*')
    name: failed-reason-excluding-health-checks
{{- else }}
apiVersion: lib.ciroos.ai/v1beta1
kind: Alert
metadata:
  name: generic-failures-alert
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  matchRules:
  - expression: resource.reason == 'Failed' && !resource.message.matches('(?i).*(health
      check|readiness|liveness).*')
    name: failed-reason-excluding-health-checks
{{- end }}