apiVersion: v1
kind: Service
metadata:
  name: k8smcp
  labels:
    app: k8smcp
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  type: {{ .Values.k8Smcp.type }}
  selector:
    app: k8smcp
    {{- include "ciroos-agents.selectorLabels" . | nindent 4 }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000