apiVersion: lib.ciroos.ai/v1beta1
kind: ResourceWatcher
metadata:
  name: pod-watcher-pullsecret
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  alwaysSend: false
  resources:
  - dependencyRules:
    - direction: outbound
      expression: |
        has(resource.spec.imagePullSecrets) ?
          resource.spec.imagePullSecrets
            .map(secret, {
              "kind": "Secret",
              "apiVersion": "v1",
              "name": secret.name,
              "namespace": resource.metadata.namespace
            }) : []
      name: image-pull-secrets
      type: security
    groupVersionKind:
      group: ""
      kind: Pod
      version: v1
    matchRules:
    - expression: "true"
      name: all-pods
    name: running-pods