{{- if .Values.namespaceScoped }}
apiVersion: lib.ciroos.ai/v1beta1
kind: NamespacedAlert
metadata:
  name: secrets-management-store-missing
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  matchRules:
    - name: store-missing
      expression: "resource.reason in ['InvalidStoreRef', 'UpdateFailed']"
{{- else }}
apiVersion: lib.ciroos.ai/v1beta1
kind: Alert
metadata:
  name: secrets-management-store-missing
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  matchRules:
    - name: store-missing
      expression: "resource.reason in ['InvalidStoreRef', 'UpdateFailed']"
{{- end }}