{{- if .Values.namespaceScoped }}
apiVersion: lib.ciroos.ai/v1beta1
kind: NamespacedAlert
metadata:
  name: secret-store-invalid-provider
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  matchRules:
    - name: invalid-provider
      expression: "resource.reason == 'InvalidProviderConfig'"
{{- else }}
apiVersion: lib.ciroos.ai/v1beta1
kind: Alert
metadata:
  name: secret-store-invalid-provider
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  matchRules:
    - name: invalid-provider
      expression: "resource.reason == 'InvalidProviderConfig'"
{{- end }}