apiVersion: v1
kind: Service
metadata:
  name: vector-service
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: Agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/name: vector
    {{- include "ciroos-agents.selectorLabels" . | nindent 4 }}
  ports:
  - name: pod-images-port
    port: 8787
    protocol: TCP
    targetPort: 8787
  - name: k8s-events-port
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: sbom-output-port
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: otlp-grpc-port
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: k8s-resources-port
    port: 8990
    protocol: TCP
    targetPort: 8990
  - name: k8s-v2-events-port
    port: 8991
    protocol: TCP
    targetPort: 8991
  - name: k8s-relationships
    port: 8992
    protocol: TCP
    targetPort: 8992
  - name: k8s-alerts-port
    port: 8993
    protocol: TCP
    targetPort: 8993
  - name: ebpf-topology-port
    port: 8994
    protocol: TCP
    targetPort: 8994
  - name: git-ops
    port: 8995
    protocol: TCP
    targetPort: 8995
  - name: k8s-resources-metrics-port
    port: 8996
    protocol: TCP
    targetPort: 8996