apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebpf-topo-reducer
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ebpfTopoReducer.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventrouter-controller
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.eventrouterController.serviceAccount.annotations | nindent 4 }}
---
{{- if .Values.sourceRepositoryWatcherController.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: source-repository-watcher-controller
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.sourceRepositoryWatcherController.serviceAccount.annotations | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8smcp-sa
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.k8SmcpSa.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector
  labels:
    app.kubernetes.io/component: Agent
  {{- include "ciroos-agents.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.vector.serviceAccount.annotations | nindent 4 }}