{{- if .Values.namespaceScoped }}
apiVersion: lib.ciroos.ai/v1beta1
kind: NamespacedAlert
metadata:
  name: pod-sandbox-creation-error-alert
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  matchRules:
    - name: failed-create-pod-sandbox
      expression: "resource.reason == 'FailedCreatePodSandBox'"
{{- else }}
apiVersion: lib.ciroos.ai/v1beta1
kind: Alert
metadata:
  name: pod-sandbox-creation-error-alert
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  matchRules:
    - name: failed-create-pod-sandbox
      expression: "resource.reason == 'FailedCreatePodSandBox'"
{{- end }}
