apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sveltos-applier-manager-read-permission
  labels:
  {{- include "ciroos.labels" . | nindent 4 }}
rules:
{{- if .Values.sveltosApplierManager.readAllResources }}
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
{{- else }}
{{ include "ciroos.sveltosApplierReadRules" . }}
{{- end }}
