apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sveltos-applier-manager-role
  labels:
  {{- include "ciroos.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sveltos-applier-manager-rolebinding
  labels:
  {{- include "ciroos.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'sveltos-applier-manager-role'
subjects:
- kind: ServiceAccount
  name: 'sveltos-applier-manager'
  namespace: 'projectsveltos'