namespaceScoped: false
clusterNamespace: ""
clusterName: "cluster-name"
ingressFqdn: ""
ciroosIngressUrl: ""
ciroosDockerconfigjson: ""
ciroosCaCrt: ""
ciroosTlsCrt: ""
ciroosTlsKey: ""
kind: Secret
beacon:
  beacon:
    image:
      repository: registry.ciroos.ai/netra/beacon
      tag: 36bae5519-6fb97227e-260616T1729Z
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
  replicas: 1
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  impersonate: false
  impersonatedServiceAccounts: []
  managePods: true
  readAllResources: true
beaconSa:
  serviceAccount:
    annotations: {}
ebpfTopoColl:
  ebpfTopoColl:
    useSysAdminCap: false
    image:
      repository: registry.ciroos.ai/netra/ebpf-topo-coll
      tag: 5d7dee2b6-8c59aa5fe-260608T1604Z
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    containerSecurityContext:
  enabled: true
  podSecurityContext:
ebpfTopoReducer:
  ebpfTopoReducer:
    image:
      repository: registry.ciroos.ai/netra/ebpf-topo-reducer
      tag: 986abf9a2-98664185e-260608T1627Z
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  replicas: 1
  serviceAccount:
    annotations: {}
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
eventrouterController:
  controller:
    image:
      repository: registry.ciroos.ai/netra/eventrouter-controller
      tag: eca5886c5-7ba600819-260609T0955Z
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccount:
    annotations: {}
eventrouterGvks:
  alertUrl: http://vector-service:8993/k8s/alerts
  dependencyEdgeUrl: http://vector-service:8998/k8s/relationships/v2
  eventUrl: http://vector-service:8991/v2/k8s/events
  heartbeatUrl: http://vector-service:8997/k8s/heartbeat
kubernetesClusterDomain: cluster.local
otelCollector:
  goMemLimit: "1536MiB"
  otelCollector:
    image:
      repository: registry.ciroos.ai/netra/otelcollector
      tag: 162b8966f-362a371b0-260528T1703Z
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  enabled: true
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
sourceRepositoryWatcherController:
  controller:
    image:
      repository: registry.ciroos.ai/netra/source-repository-watcher
      tag: 06865254d-fd6990674-260612T1505Z
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  enabled: true
  replicas: 1
  serviceAccount:
    annotations: {}
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
vector:
  vector:
    env:
      rustBacktrace: full
      vectorLog: info
    image:
      repository: registry.ciroos.ai/netra/vector
      tag: 6af8b0bca-d117f8820-260612T1850Z
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 512Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  replicas: 1
  serviceAccount:
    annotations: {}
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
insightController:
  enabled: true
  controller:
    image:
      repository: registry.ciroos.ai/netra/insight
      tag: 377e12249-184c0e30f-260616T1027Z
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 512Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccount:
    annotations: {}
nexusAgent:
  enabled: false
  controller:
    image:
      repository: registry.ciroos.ai/netra/nexus-agent
      tag: f349bb268-184c0e30f-260616T1027Z
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 500m
        memory: 256Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccount:
    annotations: {}
