namespaceScoped: false
clusterNamespace: ""
clusterName: "cluster-name"
ingressFqdn: ""
ciroosIngressUrl: ""
ciroosDockerconfigjson: ""
ciroosCaCrt: ""
ciroosTlsCrt: ""
ciroosTlsKey: ""
kind: Secret
beacon:
  beacon:
    image:
      repository: registry.ciroos.ai/netra/beacon
      tag: c9ba72811-af2615a3f-260904T1544Z
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
  replicas: 1
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  impersonate: false
  impersonatedServiceAccounts: []
  managePods: true
  readAllResources: true
beaconSa:
  serviceAccount:
    annotations: {}
ebpfTopoColl:
  ebpfTopoColl:
    useSysAdminCap: false
    image:
      repository: registry.ciroos.ai/netra/ebpf-topo-coll
      tag: d56b94234-af2615a3f-260904T1544Z
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    containerSecurityContext:
  enabled: true
  podSecurityContext:
ebpfTopoReducer:
  ebpfTopoReducer:
    image:
      repository: registry.ciroos.ai/netra/ebpf-topo-reducer
      tag: fc2602b95-af2615a3f-260904T1544Z
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  replicas: 1
  serviceAccount:
    annotations: {}
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
eventrouterController:
  controller:
    image:
      repository: registry.ciroos.ai/netra/eventrouter-controller
      tag: 5d3ab6959-958513134-260907T1321Z
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccount:
    annotations: {}
eventrouterGvks:
  alertUrl: http://vector-service:8993/k8s/alerts
  dependencyEdgeUrl: http://vector-service:8998/k8s/relationships/v2
  eventUrl: http://vector-service:8991/v2/k8s/events
  heartbeatUrl: http://vector-service:8997/k8s/heartbeat
kubernetesClusterDomain: cluster.local
otelCollector:
  goMemLimit: "1536MiB"
  otelCollector:
    image:
      repository: registry.ciroos.ai/netra/otelcollector
      tag: 089158c47-af2615a3f-260904T1544Z
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  enabled: true
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
sourceRepositoryWatcherController:
  controller:
    image:
      repository: registry.ciroos.ai/netra/source-repository-watcher
      tag: aaab7a9f2-af2615a3f-260904T1544Z
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  enabled: true
  replicas: 1
  serviceAccount:
    annotations: {}
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
vector:
  vector:
    env:
      rustBacktrace: full
      vectorLog: info
    image:
      repository: registry.ciroos.ai/netra/vector
      tag: 52d091839-af2615a3f-260904T1544Z
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 512Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  replicas: 1
  serviceAccount:
    annotations: {}
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
insightController:
  enabled: true
  controller:
    image:
      repository: registry.ciroos.ai/netra/insight
      tag: e33478504-958513134-260907T1321Z
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 512Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccount:
    annotations: {}
nexusAgent:
  enabled: false
  controller:
    image:
      repository: registry.ciroos.ai/netra/nexus-agent
      tag: 8258bd1c2-af2615a3f-260904T1544Z
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 500m
        memory: 256Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccount:
    annotations: {}
